// components/email-templates/styles.ts
import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const createStyles = (colors: any, isDark: boolean) =>
  StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.background,
    },
    searchContainer: {
      backgroundColor: colors.card,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    searchInputContainer: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: isDark ? colors.card : "#f5f5f5",
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: {
      flex: 1,
      fontSize: 16,
      color: colors.text,
      padding: 0,
      marginLeft: 8,
    },
    categoryButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: "row",
      alignItems: "center",
    },
    favoriteFilterButton: {
      padding: 8,
      borderRadius: 12,
      borderWidth: 1,
      marginLeft: 8,
    },
    createButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.primary,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 8,
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    contentContainer: {
      flex: 1,
      padding: 16,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    templateCard: {
      backgroundColor: colors.card,
      borderRadius: 12,
      padding: 16,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
      elevation: 2,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 3,
    },
    cardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
    },
    categoryIconContainer: {
      width: 24,
      height: 24,
      borderRadius: 6,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 8,
    },
    templateName: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
    },
    templateDescription: {
      fontSize: 14,
      color: colors.textSecondary,
      marginBottom: 4,
      lineHeight: 20,
    },
    templateSubject: {
      fontSize: 12,
      color: colors.textSecondary,
      marginBottom: 12,
    },
    cardFooter: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    useCountContainer: {
      flexDirection: "row",
      alignItems: "center",
    },
    useCountText: {
      fontSize: 12,
      color: colors.textSecondary,
      marginLeft: 2,
    },
    tagsContainer: {
      flexDirection: "row",
      gap: 4,
    },
    tag: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      backgroundColor: isDark ? colors.border : "#f0f0f0",
      borderRadius: 6,
    },
    tagText: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    modalContainer: {
      backgroundColor: colors.card,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      maxHeight: "90%",
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: colors.text,
    },
    infoCard: {
      backgroundColor: isDark ? colors.border : "#f5f5f5",
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
    },
    infoRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    infoLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
      marginBottom: 2,
    },
    infoValue: {
      fontSize: 16,
      color: colors.text,
    },
    variableContainer: {
      marginBottom: 16,
    },
    variableTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
      marginBottom: 8,
    },
    variableTag: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      backgroundColor: colors.primary + "20",
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.primary,
      margin: 2,
    },
    variableTagText: {
      fontSize: 12,
      color: colors.primary,
      fontFamily: "monospace",
    },
    contentContainerTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
    },
    contentPreview: {
      backgroundColor: isDark ? colors.background : "#ffffff",
      borderRadius: 12,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
      minHeight: 200,
    },
    contentTextMonospace: {
      fontSize: 14,
      color: colors.text,
      lineHeight: 22,
      fontFamily: "monospace",
    },
    modalActions: {
      flexDirection: "row",
      paddingHorizontal: 20,
      paddingVertical: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      gap: 8,
    },
    actionButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: "center",
    },
    secondaryAction: {
      backgroundColor: isDark ? colors.border : "#f0f0f0",
      borderWidth: 1,
      borderColor: colors.border,
    },
    primaryAction: {
      backgroundColor: colors.primary,
    },
    dangerAction: {
      backgroundColor: "#FF6B6B",
    },
    actionText: {
      fontSize: 16,
      fontWeight: "600",
    },
    secondaryActionText: {
      color: colors.text,
    },
    primaryActionText: {
      color: "#ffffff",
    },
    emptyStateContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 40,
    },
    emptyStateIcon: {
      width: 80,
      height: 80,
      borderRadius: 40,
      backgroundColor: colors.border,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
    },
    emptyStateTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: colors.textSecondary,
      marginBottom: 8,
    },
    emptyStateText: {
      fontSize: 16,
      color: colors.textSecondary,
      textAlign: "center",
      marginBottom: 16,
      maxWidth: "80%",
    },
    resetButton: {
      paddingHorizontal: 24,
      paddingVertical: 12,
      backgroundColor: colors.primary,
      borderRadius: 12,
      flexDirection: "row",
      alignItems: "center",
    },
    resetButtonText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#ffffff",
      marginLeft: 8,
    },
    statsContainer: {
      backgroundColor: colors.card,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      padding: 16,
    },
    statsRow: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    statItem: {
      alignItems: "center",
      flex: 1,
    },
    statValue: {
      fontSize: 24,
      fontWeight: "bold",
      marginBottom: 2,
    },
    statLabel: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    statDivider: {
      width: 1,
      backgroundColor: colors.border,
      marginHorizontal: 12,
    },
    input: {
      backgroundColor: isDark ? colors.border : "#f5f5f5",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 16,
      color: colors.text,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.text,
      marginBottom: 4,
    },
    categorySelector: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      borderWidth: 2,
      alignItems: "center",
      minWidth: 100,
    },
    variablesHelper: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      backgroundColor: isDark ? colors.border : "#f5f5f5",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      padding: 12,
      marginBottom: 12,
    },
    variablesHelperTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.text,
      marginBottom: 2,
    },
    variablesHelperText: {
      fontSize: 12,
      color: colors.textSecondary,
    },
    contentInput: {
      backgroundColor: isDark ? colors.border : "#f5f5f5",
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      fontSize: 16,
      color: colors.text,
      height: 200,
      textAlignVertical: "top",
    },
    modalScrollContent: {
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    listHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },
    filterButton: {
      flexDirection: "row",
      alignItems: "center",
    },
    filterButtonText: {
      fontSize: 12,
      color: colors.textSecondary,
      marginLeft: 4,
      marginRight: 4,
    },
    templateCount: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
    },
  });
